basic:
  application:
    name: 'tiny-api'
    type: 'microservice'

  ingress:
    host: local.me
    strip: "false"

  deployment:
    replicaCount: 1

    containers:
      - name: 'tiny-api'
        image: 'dapengwang/tiny-api:1.0.0'
        containerPort: 6666
        livenessProbe:
          httpGet:
            path: "/tiny/actuator/health"
            port: 6666
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: "/tiny/actuator/health"
            port: 6666
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ingress:
          path: /tiny/?(.*)
