{{- range .Values.deployment.containers }}
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: {{ $.Values.application.name }}
  labels:
    app.kubernetes.io/name: {{ $.Values.application.name }}
  annotations: {}
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - HEAD
      accessStrategies:
        - handler: allow
      service:
        name: {{ .name }}-service
        port: {{ .containerPort }}
  service:
    name: {{ .name }}-service
    port: {{ .containerPort }}
  host: {{ $.Values.application.name }}.b4a63c3.kyma.shoot.live.k8s-hana.ondemand.com
---
{{- end }}
