{{- range .Values.deployment.containers }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
  {{ include "metadata.labels" $ }}
spec:
  ports:
  - name: {{ .name }}-port
    port: {{ .containerPort }}
    protocol: TCP
    targetPort: {{ .containerPort }}
  selector:
    app: {{ $.Values.application.name }}
    name: {{ $.Values.application.name }}
  sessionAffinity: None
  type: ClusterIP
---
{{- end }}
