app-of-apps:
  project: memo
  namespace: memo
  path: environments/memo
  prefixAppName: false
#  defaultValueFiles:
#    - ../.environment/values.yaml
  applications:
    - name: tiny-api
    - name: admin-ui
#    - name: kong
#      namespace: kong
    - name: kong-ingress
      namespace: kong
    - name: httpbin
      namespace: gloo
#    - name: admin-manager
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions: # Sync options which modifies sync behavior
      - Validate=false
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=false
      - Replace=false
      - PrunePropagationPolicy=foreground