basic:
  application:
    name: 'vault-credentials'

  vaultStaticSecrets:
    # VCAP services
    - name: 'vcap-services-vault'
      path: vcap-services
    # Dynatrace config
    - name: 'forme-custom-credentials-vault'
      path: custom-credentials
    # Artifactory Pull Secret
    - name: 'artifactory-credential-vault'
      path: artifactory-credential