vault-secrets-operator:
  defaultVaultConnection:
    # toggles the deployment of the VaultAuthMethod CR
    enabled: true
    # Address of the Vault Server
    address: "https://vault.tools.sap/"
    skipTLSVerify: false
    spec:
    template:
      spec:
        containers:
          - name: manager
            args:
              - "--client-cache-persistence-model=direct-encrypted"
#  defaultAuthMethod:
#    enabled: true
#    mount: kyma
#    kubernetes:
#      role: "kyma-vault-secret-operator-role"
#      serviceAccount: default