# Default values for staging.
application:
  # -- primary name of the application / deployment unit
  name: '# TODO: must define a default value for name'
  # -- group name for grouping resources of the same deployment unit
  group: '# TODO: must define a default value for group'
  # -- whether deployment resource should be rendered
  deployment:
    enabled: true
  # -- whether deployment resource should be rendered
  ingress:
    enabled: true
  # -- whether cronjob resource should be rendered
  cronjob:
    enabled: false
  # -- whether job resource should be rendered
  job:
    enabled: false

# -- general ingress settings
ingress:
  standard:
    host: domain.com

# -- general deployment settings
deployment:
  # -- replica count
  replicaCount: 1
  # -- restart policy
  restartPolicy: 'Always'
  # -- image pull secret
  imagePullSecret: ''
  # -- default settings for containers
  defaults:
    # -- default resource setting
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 50m
        memory: 512Mi
    # -- default image pull policy
    imagePullPolicy: Always
    # -- default liveness probe settings
    livenessProbe:
      enabled: true
      failureThreshold: 3
      path: "/healthcheck"
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    # -- default readiness probe settings
    readinessProbe:
      enabled: true
      failureThreshold: 3
      path: "/healthcheck"
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  # -- list of containers in the pod
  containers: