# Default values for staging.
application:
  name: 'tiny-api'
  group: 'tiny-api'
  ingress:
    enabled: false
  deployment:
    enabled: true
# -- general deployment settings
deployment:
  # -- replica count
  replicaCount: 1
  # -- restart policy
  restartPolicy: 'Always'
  # -- image pull secret
  imagePullSecret: ''
  # -- default settings for containers
  defaults:
    # -- default resource setting
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 50m
        memory: 512Mi
    # -- default image pull policy
    imagePullPolicy: Always
    # -- default liveness probe settings
    livenessProbe:
      enabled: true
      failureThreshold: 3
      path: "/healthcheck"
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    # -- default readiness probe settings
    readinessProbe:
      enabled: true
      failureThreshold: 3
      path: "/healthcheck"
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
  # -- list of containers in the pod
  containers:
    - name: 'tiny-api'
      image: 'dapengwang/tiny-api:0.0.2'
      containerPort: 6666
      env:
        - name: DATABASE_URL
          value: TEST
      readinessProbe:
        path: "/tiny/actuator/health"
      livenessProbe:
        path: "/tiny/actuator/health"
