---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-service-account
  namespace: dynatrace
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-service-account-token
  namespace: dynatrace
  annotations:
    kubernetes.io/service-account.name: vault-service-account
type: kubernetes.io/service-account-token