basic:
  application:
    name: 'admin-manager'
    type: 'backend'
    statefulset:
      enabled: true
    deployment:
      enabled: false
  ingress:
    host: local.me
    strip: "false"

  statefulset:
    replicaCount: 1
    serviceAccount: admin-manager-service-account
    containers:
      - name: 'admin-manager'
        image: 'dapengwang/admin-manager:0.0.8'
        env:
          - name: MEMO_PLANT
            value: EWA
          - name: KEYCLOAK_SERVER
            value: 'https://localhost:8080/auth'
          - name: KEYCLOAK_REALM
            value: 'memo-ewa'
          - name: ADMIN_CLIENT_ID
            value: 'memo-ewa'
          - name: ADMIN_CLIENT_SECRET
            value: 'memo-ewa-secret'
          - name: SCHEDULEDJOB_ENABLED
            value: 'false'
          - name: OIDC_ENABLED
            value: 'false'
          - name: KUBERNETES_NAMESPACE
            value: 'memo'
        containerPort: 6000
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: "/admin-manager/actuator/health"
            port: 6000
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: "/admin-manager/actuator/health"
            port: 6000
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        ingress:
          path: /admin-manager/?(.*)

  serviceAccounts:
    - name: admin-manager

  roles:
    - name: admin-manager
      namespace: memo
      apiGroups:
        - '""'
        - apps
        - extensions
        - rbac.authorization.k8s.io
        - networking.k8s.io
        - memo.siemens.com
      resources:
        - pods
        - configmaps
        - deployments
        - replicasets
        - services
        - ingresses
        - scheduledjobs
        - scheduledjobs/status
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
        - "watch"

  roleBindings:
    - name: admin-manager
      role: admin-manager-role
      serviceAccount: admin-manager-service-account
      namespace: memo
