apiVersion: v1
kind: Service
metadata:
  labels:
    app: tiny-api
  name: tiny-api-service
spec:
  ports:
  - name: tiny-api-port
    port: 6666
    protocol: TCP
    targetPort: 6666
  selector:
    app: tiny-api
    name: tiny-api
  sessionAffinity: None
  type: ClusterIP
