basic:
  application:
    name: 'tiny-api'

  deployment:
    replicaCount: 1

    containers:
      - name: 'tiny-api'
      - name: 'tiny-api-helm'
        image: 'dapengwang/tiny-api:0.0.2'
        containerPort: 6666
        livenessProbe:
          enabled: true
          failureThreshold: 3
          path: "/tiny/actuator/health"
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        # -- default readiness probe settings
        readinessProbe:
          enabled: true
          failureThreshold: 3
          path: "/tiny/actuator/health"
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
