# Default values for staging.
application:
  # -- primary name of the application / deployment unit
  name: '# TODO: must define a default value for name'

# -- general deployment settings
deploymentDefaults:
  # -- istio sidecar enabled
  istioEnabled: false
  # -- replica count
  replicaCount: 1
  # -- restart policy
  restartPolicy: 'Always'
  # -- image pull secret
  imagePullSecret: ''
  # -- default resource setting
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 128Mi
  # -- default image pull policy
  imagePullPolicy: Always


# -- general statefulset settings
statefulsetDefaults:
  # -- istio sidecar enabled
  istioEnabled: false
  # -- replica count
  replicaCount: 1
  # -- restart policy
  restartPolicy: 'Always'
  # -- image pull secret
  imagePullSecret: ''
  # -- default resource setting
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 128Mi
  # -- default image pull policy
  imagePullPolicy: Always