{{- range .Values.nodes }}
{{- if (list nil true "true" | has .hpa) }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: {{ .name | replace "_" "-" | lower | trim | quote }}
  labels: {{- include "app.labels" $ | nindent 4 }}
    app.kubernetes.io/part-of: {{ .name }}

spec:
  {{- $minReplicas := .replicas | default (default 1 $.Values.replicaCount) }}
  maxReplicas: {{ add $minReplicas 5 }}
  minReplicas: {{ $minReplicas }}

  behavior:
    # scaleDown:
    #   stabilizationWindowSeconds: 120
    #   policies:
    #     - type: Percent
    #       value: 10
    #       periodSeconds: 15

    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .name | replace "_" "-" | lower | trim | quote }}

  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
{{- end }}
{{- end }}