kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patch-configmaps
  labels: {{- include "app.labels" $ | nindent 4 }}
rules:
  - verbs:
      - get
      - patch
    apiGroups:
      - ''
    resources:
      - configmaps
