{{- /*
The service account of the forme application.
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: true
---
{{- /*
We need to set automountServiceAccountToken to false and create
a secret by our own, since we need a long-living token. This is
necessary for newer Kubernetes versions (v1.22+), since the tokens
have a bounded lifetime.
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- $accountName := printf "%s-technical-user-sa" (include "app.fullname" .) }}
  name: {{ $accountName }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  {{- $secret := printf "%s-technical-user-sa-token" (include "app.fullname" .) }}
  name: {{ $secret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ $accountName }}
type: kubernetes.io/service-account-token
