{{- if .Values.clusterRoleBindings }}
{{- range $roleBinding := .Values.clusterRoleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $roleBinding.name }}-role-binding
  {{ include "metadata.labels" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $roleBinding.role }}
subjects:
  - kind: ServiceAccount
    name: {{ $roleBinding.serviceAccount }}
    namespace: {{ $roleBinding.namespace }}
{{- end }}
{{- end }}