{{- if .Values.secrets }}
{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  {{ include "metadata.namespace" $ }}
  {{ include "metadata.labels" $ }}
  {{ if eq $secret.type "kubernetes.io/service-account-token" -}}
  annotations:
    {{ toYaml .annotations | trim }}
  {{- end }}
type: {{ $secret.type | default "Opaque"}}
{{- if hasKey $secret "data" }}
data:
  {{- range $data := $secret.data }}
    {{ $data.key }}: {{ $data.value | b64enc }}
  {{- end -}}
{{- end }}
{{- end }}
{{- end }}
