{{- if .Values.vaultStaticSecrets }}
{{- range $secret := .Values.vaultStaticSecrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $secret.name }}
  {{ include "metadata.namespace" $ }}
  {{ include "metadata.labels" $ }}
spec:
  type: {{ $secret.type | default "kv-v2" }}
  mount: {{ $secret.mount | default "kv" }}
  path: {{ $secret.path }}
  destination:
    name: {{ $secret.name }}
    create: {{ $secret.create | default "true" }}
  refreshAfter: {{ $secret.refreshAfter | default "60s" }}
  vaultAuthRef: {{ $secret.vaultAuthRef | default "vault-auth" }}
{{- end }}
{{- end }}
