landscape: dev

image:
  repository: dev

health:
  liveness:
    path: /raw/public/core/IsolatedPingTest

tracing:
  enabled: true

logging:
  enabled: true

artifactory:
  endpoint: http://int.repositories.cloud.sap:443/artifactory/api/npm/forme-npm-snapshot/@forme
  cloudConnector: SCC-INT-D1

clusters:
  refresher:
    interval: "0$[0123456789]"

redeployMissingEntities: false

xsuaa:
  verificationkey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyQng3M1RTRnJpZ25oRHoyWlV2UApzWXBuY1FSWjZFbm5kRWxDdElrM01uMTh0NVYwdDhLYlFzblZLMEJTVk40dEhzZzVvRU0xbnlZV0RUbFhMWmZUCjR6RmdWYXUycGprTkwwZHBKR21URkJtUHZLdG42MnVHSHYvWHRqd0Jtd0VrQ2h2VE1ualZ1VGxVTXIvcDVxZWMKTTMvL1cvQmh6Szg1bGVWemxkS3BUV09YaDNKNHZFbm16RWRWUzFydEpsQ2d1eGFCN1R1ZUdHdjdEbHA5Q0xIOApqWm11NkFWYk9DUjJJWnFsSkVYMy9vWVNtbjFMSGdRbFJaUFQ1Yk1tMFVkZXdyUDVXcUJ3ZG0xeUt6VDJLNk9TClZIR0JobFJRQUxZRGRDcXhFQ2tLOFlCQTBZNXI5eEIwdnBvVmZNZC9TVXRPb3NOaHNHZWZMbjdGTUxTR0RIdGgKb3dJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  xsappname: forme-approuter!t1329

platformServices:
  - service: feature-flags
    plan: standard
  - service: connectivity
    plan: connectivity_proxy
  - service: auditlog
    plan: oauth2
  - service: auditlog-management
    plan: default
  - service: destination
    plan: lite
  - service: credstore
    plan: medium
  - service: cloud-logging
    plan: standard
  # HANA HDI containers
  - service: hana
    plan: hdi-shared
    name: forme-hana-forme-db
    parameters:
      schema: FORME
# further HDI instances are added based on the dbModels in btp-services.yaml

dbModels: [] # the DB models will be copied over from the meta-configuration.yml, the version of will be added during Gradle landscape build

nodes: [] # will be copied over from meta-configuration.yml