{{- range $config := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $config.name }}
  {{ include "metadata.labels" $ }}
data:
{{- range $data := $config.data }}
  {{ if $data.multiline -}}
  {{ $data.key }}: |+
{{ tpl $data.value $ | indent 4 }}
  {{- else -}}
  {{ $data.key }}: {{ $data.value | squote }}
  {{ end }}
{{- end -}}
{{- end }}