{{- if .Values.secrets }}
{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  {{ include "metadata.labels" $ }}
type: {{ $secret.type | default "Opaque"}}
data:
  {{- range $data := $secret.data }}
    {{ $data.key }}: {{ $data.value | b64enc }}
  {{- end -}}
{{- end }}
{{- end }}
