  {{- range $serviceAccount := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name }}-service-account
  {{ include "metadata.labels" $ }}
  {{- end }}